name: luthor
repository: https://github.com/exaby73/luthor

packages:
  - packages/*

scripts:
  analyze:
    run: dart analyze

  format:
    run: dart format --set-exit-if-changed .

  test:
    exec: dart test
    packageFilters:
      scope:
        - luthor
