name: luthor_annotation
description: Annotation for luthor_generator
version: 0.1.0
repository: https://github.com/exaby73/luthor/tree/main/packages/luthor_annotation

environment:
  sdk: '>=2.19.5 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
