name: luthor_annotation
description: Annotation for luthor_generator
version: 0.2.0
repository: https://github.com/exaby73/luthor/tree/main/packages/luthor_annotation

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
