builders:
  luthor:
    import: "package:luthor_generator/builder.dart"
    builder_factories: [ "luthorBuilder" ]
    build_extensions: { ".dart": [ ".luthor.dart" ] }
    auto_apply: dependents
    build_to: source
