name: luthor_generator
description: Generate luthor schemas with Freezed
version: 0.2.3
repository: https://github.com/exaby73/luthor/tree/main/packages/luthor_generator

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^5.10.0
  build: ^2.3.1
  collection: ^1.17.0
  json_annotation: ^4.0.0
  luthor_annotation: ^0.2.0
  source_gen: ^1.2.7

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0
